version: '3.9'

services:
  client:
    build: ./client
    # restart: always
    ports:
      - '3333:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    build: ./server
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      DB_NAME: fc_radzymin_db
      DB_HOST: postgres
      DB_PORT: '5432'
      DB_USER: fc_radzymin
      DB_PASSWORD: secret
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: fc_radzymin_db
      POSTGRES_USER: fc_radzymin
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "fc_radzymin_db"]
      timeout: 20s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
volumes:
  postgres_data: