version: '3.9'

services:
  client:
    build: ./client
    restart: always
    ports:
      - '3333:3333'
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    build: ./server
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: root
      POSTGRES_PORT: '3306'
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fc_radzymin
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fc_radzymin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
volumes:
  mysql_data: